from __future__ import annotations

import hashlib
import json
import threading
import uuid
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from typing import Any

from .eventlog import EventLog, SYSTEM_SESSION_ID
from .policy import PolicyEngine
from .types import (
    AdminStateOut,
    Approval,
    ApprovalStatus,
    OpRequestOut,
    SafetyLevel,
    Task,
    TaskStatus,
)


def _now() -> datetime:
    return datetime.now(timezone.utc)


@dataclass
class SessionInfo:
    session_id: str
    channel: str
    conversation_key: str
    created_at: datetime
    updated_at: datetime


class SupervisorState:
    """In-memory derived state + persistence via EventLog."""

    def __init__(
        self,
        *,
        eventlog: EventLog,
        policy: PolicyEngine,
    ) -> None:
        self.eventlog = eventlog
        self.policy = policy
        self.started_at = _now()

        self._lock = threading.Lock()

        self.sessions: dict[str, SessionInfo] = {}
        self.conversation_map: dict[str, str] = {}  # conversation_key -> session_id

        self.tasks: dict[str, Task] = {}
        self._pending_task_ids: list[str] = []

        self.approvals: dict[str, Approval] = {}

        # Worker health (best-effort): updated by API endpoints.
        # - kernel: updated whenever /v1/tasks/next is called.
        self._kernel_last_seen_at: datetime | None = None
        self._kernel_last_worker_id: str | None = None

        # Inbound routing queue (for Shell Orchestrator Worker)
        # - Items are identified by the EventLog global seq (inbound_message event).
        # - Completion is persisted via a separate event type: inbound_processed.
        self._inbound_order: list[int] = []
        self._inbound_events: dict[int, dict[str, Any]] = {}  # inbound_seq -> {session_id, payload}
        self._inbound_processed: set[int] = set()
        # Inbound routing result (idempotency): inbound_seq -> route info.
        #
        # Recorded when an inbound message is *successfully* handled by the Shell Orchestrator worker,
        # either by producing a direct reply (outbound_message with source_inbound_seq)
        # or by creating a Kernel task (task_created with source_inbound_seq).
        #
        # This allows:
        # - Deduplication across retries/crashes
        # - Skipping already-routed inbound messages even if ack was not recorded
        self._inbound_routed: dict[int, dict[str, Any]] = {}
        self._inbound_cursor: int = 0

        @dataclass
        class _InboundLease:
            worker_id: str
            expires_at: datetime

        self._InboundLease = _InboundLease  # stash type to avoid top-level export
        self._inbound_leases: dict[int, _InboundLease] = {}

        # ----------------------------
        # Completed task result queue (for Shell Responder / chat AI)
        # ----------------------------
        #
        # Goal: When Kernel finishes a task, we want the *final user-facing reply*
        # to be generated by a chat AI (Shell), not by the Kernel executor.
        #
        # Therefore:
        # - Kernel only writes task_completed (with result draft).
        # - Shell polls this queue, post-processes the result via LLM,
        #   then appends an outbound_message with source_task_id for idempotency.

        # Order of completed tasks that require a user-facing response.
        self._task_result_order: list[str] = []
        self._task_result_seen: set[str] = set()
        # task_id -> reply info (set when an outbound_message with source_task_id is appended)
        self._task_replied: dict[str, dict[str, Any]] = {}
        self._task_result_cursor: int = 0

        @dataclass
        class _TaskResultLease:
            worker_id: str
            expires_at: datetime

        self._TaskResultLease = _TaskResultLease
        self._task_result_leases: dict[str, _TaskResultLease] = {}

        self.rebuild_from_events(eventlog.events)

    def mark_kernel_seen(self, *, worker_id: str) -> None:
        with self._lock:
            self._kernel_last_seen_at = _now()
            self._kernel_last_worker_id = worker_id

    def kernel_seen_snapshot(self) -> tuple[datetime | None, str | None]:
        with self._lock:
            return self._kernel_last_seen_at, self._kernel_last_worker_id

    def rebuild_from_events(self, events: list[dict[str, Any]]) -> None:
        # MVP: 线性回放
        for e in events:
            et = e.get("type")
            session_id = e.get("session_id")
            payload = e.get("payload") or {}

            try:
                seq = int(e.get("seq", 0))
            except Exception:
                seq = 0

            if et == "session_created":
                self._apply_session_created(session_id, payload)
            elif et == "inbound_message":
                conv = payload.get("conversation_key")
                if isinstance(conv, str) and session_id:
                    self.conversation_map[conv] = session_id

                self._apply_inbound_message(seq=seq, session_id=str(session_id or ""), payload=payload)
            elif et == "inbound_processed":
                self._apply_inbound_processed(payload)
            elif et == "outbound_message":
                self._apply_outbound_message(seq=seq, session_id=str(session_id or ""), payload=payload)
            elif et == "task_created":
                self._apply_task_created(payload)
            elif et == "task_assigned":
                self._apply_task_assigned(payload)
            elif et == "task_completed":
                self._apply_task_completed(payload)
            elif et == "approval_requested":
                self._apply_approval_requested(payload)
            elif et == "approval_decided":
                self._apply_approval_decided(payload)

        self._advance_inbound_cursor()
        self._advance_task_result_cursor()

    def _advance_inbound_cursor(self) -> None:
        while self._inbound_cursor < len(self._inbound_order):
            seq = self._inbound_order[self._inbound_cursor]
            if seq in self._inbound_processed or seq in self._inbound_routed:
                self._inbound_cursor += 1
                continue
            return

    def _advance_task_result_cursor(self) -> None:
        while self._task_result_cursor < len(self._task_result_order):
            task_id = self._task_result_order[self._task_result_cursor]
            if task_id in self._task_replied:
                self._task_result_cursor += 1
                continue
            return

    def _apply_inbound_message(self, *, seq: int, session_id: str, payload: dict[str, Any]) -> None:
        if not isinstance(seq, int) or seq <= 0:
            return
        if not session_id:
            return
        if not isinstance(payload, dict):
            return

        if seq in self._inbound_events:
            return

        self._inbound_events[seq] = {"session_id": session_id, "payload": payload}
        self._inbound_order.append(seq)

    def _apply_inbound_processed(self, payload: dict[str, Any]) -> None:
        if not isinstance(payload, dict):
            return
        inbound_seq = payload.get("inbound_seq")
        try:
            seq = int(inbound_seq) if inbound_seq is not None else 0
        except Exception:
            seq = 0
        if seq > 0:
            self._inbound_processed.add(seq)

    def _apply_outbound_message(self, *, seq: int, session_id: str, payload: dict[str, Any]) -> None:
        """Apply an outbound_message event.

        Responsibilities:
        - Inbound routing dedup: if payload contains `source_inbound_seq`, record that the
          inbound message has been replied (direct reply path).
        - Completed task reply dedup: if payload contains `source_task_id` (or legacy `task_id`
          from kernel-emitted outbound_message), record that the task has produced a final
          user-facing reply.
        """

        if not session_id:
            return
        if not isinstance(payload, dict):
            return

        # 1) Direct reply dedup (inbound_seq -> reply)
        src = payload.get("source_inbound_seq")
        try:
            inbound_seq = int(src) if src is not None else 0
        except Exception:
            inbound_seq = 0

        if inbound_seq > 0:
            # Best-effort session consistency check (avoid cross-session poisoning).
            evt = self._inbound_events.get(inbound_seq)
            if isinstance(evt, dict):
                sid = str(evt.get("session_id") or "")
                if sid and sid != session_id:
                    return

            if inbound_seq not in self._inbound_routed:
                self._inbound_routed[inbound_seq] = {
                    "action": "reply",
                    "session_id": session_id,
                    "event_seq": int(seq or 0),
                }

        # 2) Task reply dedup (task_id -> replied)
        raw_task_id = payload.get("source_task_id")
        if not isinstance(raw_task_id, str) or not raw_task_id.strip():
            # backward compatibility: kernel used to emit outbound_message via /v1/tasks/{id}/events
            # which injects payload.task_id.
            raw_task_id = payload.get("task_id")

        task_id = raw_task_id.strip() if isinstance(raw_task_id, str) else ""
        if not task_id:
            return

        t = self.tasks.get(task_id)
        if t is None:
            return
        if t.session_id != session_id:
            return

        if task_id not in self._task_replied:
            self._task_replied[task_id] = {
                "session_id": session_id,
                "event_seq": int(seq or 0),
            }
            self._task_result_leases.pop(task_id, None)

    def record_inbound_message_event(self, evt: dict[str, Any]) -> None:
        """Update in-memory inbound queue when /v1/inbound appends an event."""

        if not isinstance(evt, dict):
            return
        if evt.get("type") != "inbound_message":
            return

        try:
            seq = int(evt.get("seq", 0))
        except Exception:
            seq = 0

        session_id = str(evt.get("session_id") or "")
        payload = evt.get("payload") or {}
        if not isinstance(payload, dict):
            return

        with self._lock:
            self._apply_inbound_message(seq=seq, session_id=session_id, payload=payload)
            self._advance_inbound_cursor()

    def record_outbound_message_event(self, evt: dict[str, Any]) -> None:
        """Update in-memory derived state when an outbound_message event is appended.

        Most outbound messages are appended via `append_outbound_message()` which already
        updates in-memory state.

        However, Kernel can emit `outbound_message` via `/v1/tasks/{task_id}/events`.
        In that case, Supervisor API appends the event directly to EventLog and we need
        this hook to update task-reply dedup state.
        """

        if not isinstance(evt, dict):
            return
        if evt.get("type") != "outbound_message":
            return

        try:
            seq = int(evt.get("seq", 0))
        except Exception:
            seq = 0

        session_id = str(evt.get("session_id") or "")
        payload = evt.get("payload") or {}
        if not session_id or not isinstance(payload, dict):
            return

        with self._lock:
            self._apply_outbound_message(seq=seq, session_id=session_id, payload=payload)
            self._advance_inbound_cursor()
            self._advance_task_result_cursor()

    def assign_next_inbound(self, *, worker_id: str, lease_sec: float = 30.0) -> dict[str, Any] | None:
        wid = (worker_id or "").strip()
        if not wid:
            return None

        try:
            lease_val = float(lease_sec)
        except Exception:
            lease_val = 30.0
        if lease_val < 1.0:
            lease_val = 1.0
        if lease_val > 600.0:
            lease_val = 600.0

        now = _now()

        with self._lock:
            # expire leases
            for seq, lease in list(self._inbound_leases.items()):
                if lease.expires_at <= now:
                    self._inbound_leases.pop(seq, None)

            self._advance_inbound_cursor()

            for i in range(self._inbound_cursor, len(self._inbound_order)):
                seq = self._inbound_order[i]
                if seq in self._inbound_processed or seq in self._inbound_routed:
                    if i == self._inbound_cursor:
                        self._inbound_cursor += 1
                    self._inbound_leases.pop(seq, None)
                    continue

                lease = self._inbound_leases.get(seq)
                if lease is not None and lease.expires_at > now:
                    continue

                evt = self._inbound_events.get(seq)
                if not isinstance(evt, dict):
                    continue

                session_id = str(evt.get("session_id") or "")
                payload = evt.get("payload")
                if not session_id or not isinstance(payload, dict):
                    continue

                self._inbound_leases[seq] = self._InboundLease(
                    worker_id=wid,
                    expires_at=now + timedelta(seconds=lease_val),
                )

                # Return a flattened work item.
                return {
                    "inbound_seq": seq,
                    "session_id": session_id,
                    **payload,
                }

            return None

    def ack_inbound(self, *, inbound_seq: int, worker_id: str) -> bool:
        wid = (worker_id or "").strip()
        if not wid:
            return False

        try:
            seq = int(inbound_seq)
        except Exception:
            seq = 0
        if seq <= 0:
            return False

        with self._lock:
            if seq in self._inbound_processed:
                return True
            if seq not in self._inbound_events:
                return False

            # Persist ack as an event for restart recovery.
            # NOTE: we append first, then update in-memory state, so a failed append
            # does not accidentally "lose" the inbound item in the running supervisor.
            self.eventlog.append(
                session_id=SYSTEM_SESSION_ID,
                component="shell",
                type_="inbound_processed",
                payload={"inbound_seq": seq, "worker_id": wid, "ts": _now().isoformat()},
            )

            self._inbound_processed.add(seq)
            self._inbound_leases.pop(seq, None)
            self._advance_inbound_cursor()
            return True

    def assign_next_task_result(self, *, worker_id: str, lease_sec: float = 30.0) -> Task | None:
        """Assign a completed task to a Shell worker for post-processing.

        The assigned worker should:
        - Call LLM (chat AI) to generate the final user-facing reply.
        - Append an outbound_message with `source_task_id` for idempotency.
        """

        wid = (worker_id or "").strip()
        if not wid:
            return None

        try:
            lease_val = float(lease_sec)
        except Exception:
            lease_val = 30.0
        if lease_val < 1.0:
            lease_val = 1.0
        if lease_val > 600.0:
            lease_val = 600.0

        now = _now()

        with self._lock:
            # expire leases
            for tid, lease in list(self._task_result_leases.items()):
                if lease.expires_at <= now:
                    self._task_result_leases.pop(tid, None)

            self._advance_task_result_cursor()

            for i in range(self._task_result_cursor, len(self._task_result_order)):
                task_id = self._task_result_order[i]

                if task_id in self._task_replied:
                    if i == self._task_result_cursor:
                        self._task_result_cursor += 1
                    self._task_result_leases.pop(task_id, None)
                    continue

                lease = self._task_result_leases.get(task_id)
                if lease is not None and lease.expires_at > now:
                    continue

                t = self.tasks.get(task_id)
                if t is None:
                    continue

                # Only hand out completed tasks (done/failed) that came from a user inbound.
                if t.status not in {TaskStatus.done, TaskStatus.failed}:
                    continue
                if getattr(t, "source_inbound_seq", None) is None:
                    continue

                self._task_result_leases[task_id] = self._TaskResultLease(
                    worker_id=wid,
                    expires_at=now + timedelta(seconds=lease_val),
                )
                return t

            return None

    def _apply_session_created(self, session_id: str, payload: dict[str, Any]) -> None:
        try:
            created_at = datetime.fromisoformat(payload.get("created_at"))
        except Exception:
            created_at = _now()

        info = SessionInfo(
            session_id=session_id,
            channel=str(payload.get("channel", "unknown")),
            conversation_key=str(payload.get("conversation_key", "")),
            created_at=created_at,
            updated_at=created_at,
        )
        self.sessions[session_id] = info
        if info.conversation_key:
            self.conversation_map[info.conversation_key] = session_id

    def _apply_task_created(self, payload: dict[str, Any]) -> None:
        try:
            t = Task.model_validate(payload)
        except Exception:
            return
        self.tasks[t.task_id] = t
        if t.status == TaskStatus.pending and t.task_id not in self._pending_task_ids:
            self._pending_task_ids.append(t.task_id)

        # If this task was created as the result of routing a specific inbound message,
        # record the mapping so we can dedupe retries.
        src = getattr(t, "source_inbound_seq", None)
        if isinstance(src, int) and src > 0 and src not in self._inbound_routed:
            self._inbound_routed[src] = {
                "action": "task",
                "session_id": t.session_id,
                "task_id": t.task_id,
            }

    def _apply_task_assigned(self, payload: dict[str, Any]) -> None:
        task_id = payload.get("task_id")
        if task_id in self.tasks:
            t = self.tasks[task_id]
            t.status = TaskStatus.running
            t.assigned_to = payload.get("assigned_to")
            t.updated_at = _now()
            if task_id in self._pending_task_ids:
                self._pending_task_ids.remove(task_id)

    def _apply_task_completed(self, payload: dict[str, Any]) -> None:
        task_id = payload.get("task_id")
        if task_id in self.tasks:
            t = self.tasks[task_id]
            status = payload.get("status")
            try:
                t.status = TaskStatus(status)
            except Exception:
                t.status = TaskStatus.done
            t.result = payload.get("result")
            t.updated_at = _now()
            if task_id in self._pending_task_ids:
                self._pending_task_ids.remove(task_id)

            # If this task corresponds to a user inbound message, enqueue it for
            # Shell post-processing (chat AI) so the final user-facing reply is
            # generated in the Shell layer.
            try:
                src_inbound = getattr(t, "source_inbound_seq", None)
            except Exception:
                src_inbound = None

            if src_inbound is not None and t.status in {TaskStatus.done, TaskStatus.failed}:
                if t.task_id not in self._task_replied and t.task_id not in self._task_result_seen:
                    self._task_result_seen.add(t.task_id)
                    self._task_result_order.append(t.task_id)

    def _apply_approval_requested(self, payload: dict[str, Any]) -> None:
        try:
            a = Approval.model_validate(payload)
        except Exception:
            return
        self.approvals[a.approval_id] = a

    def _apply_approval_decided(self, payload: dict[str, Any]) -> None:
        approval_id = payload.get("approval_id")
        if approval_id in self.approvals:
            a = self.approvals[approval_id]
            decision = payload.get("decision")
            a.status = ApprovalStatus.allowed if decision == "allow" else ApprovalStatus.denied
            a.decision = decision
            a.comment = payload.get("comment")
            a.decided_at = _now()

    def get_or_create_session(self, *, channel: str, conversation_key: str) -> str:
        with self._lock:
            if conversation_key in self.conversation_map:
                return self.conversation_map[conversation_key]

            session_id = str(uuid.uuid4())
            created_at = _now()

            self.sessions[session_id] = SessionInfo(
                session_id=session_id,
                channel=channel,
                conversation_key=conversation_key,
                created_at=created_at,
                updated_at=created_at,
            )
            self.conversation_map[conversation_key] = session_id

            self.eventlog.append(
                session_id=session_id,
                component="supervisor",
                type_="session_created",
                payload={
                    "session_id": session_id,
                    "channel": channel,
                    "conversation_key": conversation_key,
                    "created_at": created_at.isoformat(),
                },
            )

            return session_id

    def append_outbound_message(
        self,
        *,
        session_id: str,
        text: str,
        source_inbound_seq: int | None = None,
        source_task_id: str | None = None,
    ) -> dict[str, Any]:
        """Append an assistant message into the session event log.

        Used by Shell in two scenarios:
        1) Direct reply path (no task): provide `source_inbound_seq` for idempotency.
        2) Task post-processing path: provide `source_task_id` so Shell can generate
           exactly-once user-facing replies *after* Kernel completes a task.
        """

        text_clean = str(text or "").strip()
        if not text_clean:
            raise ValueError("empty text")

        src_seq: int | None = None
        if source_inbound_seq is not None:
            try:
                v = int(source_inbound_seq)
            except Exception:
                v = 0
            if v > 0:
                src_seq = v

        task_id_key: str | None = None
        if source_task_id is not None:
            s = str(source_task_id or "").strip()
            if s:
                task_id_key = s

        with self._lock:
            if session_id not in self.sessions:
                raise KeyError("session not found")

            if src_seq is not None and task_id_key is not None:
                raise ValueError("cannot provide both source_inbound_seq and source_task_id")

            if src_seq is not None:
                inbound_evt = self._inbound_events.get(src_seq)
                if not isinstance(inbound_evt, dict):
                    raise ValueError(f"source_inbound_seq not found: {src_seq}")
                if str(inbound_evt.get("session_id") or "") != session_id:
                    raise ValueError("source_inbound_seq session mismatch")

                existing = self._inbound_routed.get(src_seq)
                if isinstance(existing, dict):
                    if existing.get("action") == "reply":
                        return {"ok": True, "deduped": True, "route": existing}
                    raise RuntimeError("inbound_seq already routed to task")

            if task_id_key is not None:
                t = self.tasks.get(task_id_key)
                if t is None:
                    raise ValueError(f"source_task_id not found: {task_id_key}")
                if t.session_id != session_id:
                    raise ValueError("source_task_id session mismatch")

                existing_task = self._task_replied.get(task_id_key)
                if isinstance(existing_task, dict):
                    return {"ok": True, "deduped": True, "task": existing_task}

            payload: dict[str, Any] = {"text": text_clean}
            if src_seq is not None:
                payload["source_inbound_seq"] = src_seq
            if task_id_key is not None:
                payload["source_task_id"] = task_id_key

            evt = self.eventlog.append(
                session_id=session_id,
                component="shell",
                type_="outbound_message",
                payload=payload,
            )

            if src_seq is not None and src_seq not in self._inbound_routed:
                self._inbound_routed[src_seq] = {
                    "action": "reply",
                    "session_id": session_id,
                    "event_seq": int(evt.get("seq", 0) or 0),
                }

            if task_id_key is not None and task_id_key not in self._task_replied:
                self._task_replied[task_id_key] = {
                    "session_id": session_id,
                    "event_seq": int(evt.get("seq", 0) or 0),
                }
                self._task_result_leases.pop(task_id_key, None)
                self._advance_task_result_cursor()

            return {"ok": True, "deduped": False, "event_seq": int(evt.get("seq", 0) or 0)}

    def create_task(
        self,
        *,
        session_id: str,
        instruction: str,
        priority: int = 0,
        context: dict[str, Any] | None = None,
        source_inbound_seq: int | None = None,
        use_context: bool = True,
    ) -> Task:
        context = context or {}

        src_seq: int | None = None
        if source_inbound_seq is not None:
            try:
                v = int(source_inbound_seq)
            except Exception:
                v = 0
            if v > 0:
                src_seq = v

        with self._lock:
            # Idempotency & conflict guard (only when source_inbound_seq is provided)
            if src_seq is not None:
                inbound_evt = self._inbound_events.get(src_seq)
                if not isinstance(inbound_evt, dict):
                    raise ValueError(f"source_inbound_seq not found: {src_seq}")
                if str(inbound_evt.get("session_id") or "") != session_id:
                    raise ValueError("source_inbound_seq session mismatch")

                existing = self._inbound_routed.get(src_seq)
                if isinstance(existing, dict):
                    if existing.get("action") == "task":
                        tid = existing.get("task_id")
                        if isinstance(tid, str) and tid in self.tasks:
                            return self.tasks[tid]
                    else:
                        raise RuntimeError("inbound_seq already routed to reply")

            now = _now()
            task = Task(
                task_id=str(uuid.uuid4()),
                session_id=session_id,
                instruction=instruction,
                source_inbound_seq=src_seq,
                use_context=use_context,
                status=TaskStatus.pending,
                priority=priority,
                created_at=now,
                updated_at=now,
                assigned_to=None,
                result=None,
            )
            self.tasks[task.task_id] = task
            self._pending_task_ids.append(task.task_id)

            # 以 payload 形式写入（便于重放）
            self.eventlog.append(
                session_id=session_id,
                component="supervisor",
                type_="task_created",
                payload=task.model_dump(mode="json"),
            )

            if src_seq is not None and src_seq not in self._inbound_routed:
                self._inbound_routed[src_seq] = {
                    "action": "task",
                    "session_id": session_id,
                    "task_id": task.task_id,
                }

            return task

    def assign_next_task(self, *, worker_id: str) -> Task | None:
        with self._lock:
            if not self._pending_task_ids:
                return None

            # MVP: FIFO（可后续按 priority 排序）
            task_id = self._pending_task_ids.pop(0)
            t = self.tasks[task_id]
            t.status = TaskStatus.running
            t.assigned_to = worker_id
            t.updated_at = _now()

            self.eventlog.append(
                session_id=t.session_id,
                component="supervisor",
                type_="task_assigned",
                payload={
                    "task_id": t.task_id,
                    "session_id": t.session_id,
                    "assigned_to": worker_id,
                    "ts": _now().isoformat(),
                },
            )

            return t

    def complete_task(self, *, task_id: str, status: TaskStatus, result: dict[str, Any]) -> Task | None:
        with self._lock:
            if task_id not in self.tasks:
                return None

            t = self.tasks[task_id]
            t.status = status
            t.result = result
            t.updated_at = _now()

            self.eventlog.append(
                session_id=t.session_id,
                component="supervisor",
                type_="task_completed",
                payload={
                    "task_id": task_id,
                    "session_id": t.session_id,
                    "status": status.value,
                    "result": result,
                    "ts": _now().isoformat(),
                },
            )

            src_inbound = getattr(t, "source_inbound_seq", None)
            if src_inbound is not None and status in {TaskStatus.done, TaskStatus.failed}:
                if t.task_id not in self._task_replied and t.task_id not in self._task_result_seen:
                    self._task_result_seen.add(t.task_id)
                    self._task_result_order.append(t.task_id)
                    self._advance_task_result_cursor()

            return t

    def create_approval(self, *, session_id: str, operation: str, details: dict[str, Any]) -> Approval:
        now = _now()
        fingerprint_src = json.dumps({"operation": operation, "details": details}, sort_keys=True, ensure_ascii=False)
        fingerprint = hashlib.sha256(fingerprint_src.encode("utf-8")).hexdigest()[:12]

        approval = Approval(
            approval_id=str(uuid.uuid4()),
            session_id=session_id,
            operation=operation,
            details=details,
            status=ApprovalStatus.pending,
            fingerprint=fingerprint,
            requested_at=now,
            decided_at=None,
            decision=None,
            comment=None,
        )

        with self._lock:
            self.approvals[approval.approval_id] = approval

        self.eventlog.append(
            session_id=session_id,
            component="supervisor",
            type_="approval_requested",
            payload=approval.model_dump(mode="json"),
        )

        return approval

    def decide_approval(self, *, approval_id: str, decision: str, comment: str | None = None) -> Approval | None:
        with self._lock:
            if approval_id not in self.approvals:
                return None
            a = self.approvals[approval_id]
            a.decision = "allow" if decision == "allow" else "deny"
            a.status = ApprovalStatus.allowed if a.decision == "allow" else ApprovalStatus.denied
            a.comment = comment
            a.decided_at = _now()

        self.eventlog.append(
            session_id=a.session_id,
            component="supervisor",
            type_="approval_decided",
            payload={
                "approval_id": approval_id,
                "session_id": a.session_id,
                "decision": a.decision,
                "comment": comment,
                "ts": _now().isoformat(),
            },
        )

        return a

    def request_operation(self, *, session_id: str, op: str, parameters: dict[str, Any]) -> OpRequestOut:
        decision = self.policy.evaluate(op=op, parameters=parameters)

        if decision.safety_level == SafetyLevel.deny:
            return OpRequestOut(safety_level=SafetyLevel.deny, reason=decision.reason, approval_id=None)

        if decision.safety_level == SafetyLevel.auto:
            return OpRequestOut(safety_level=SafetyLevel.auto, reason=decision.reason, approval_id=None)

        approval = self.create_approval(session_id=session_id, operation=op, details=parameters)
        return OpRequestOut(
            safety_level=SafetyLevel.approval_required,
            reason=decision.reason,
            approval_id=approval.approval_id,
        )

    def list_events(self, *, session_id: str, after_seq: int) -> list[dict[str, Any]]:
        return self.eventlog.list_events(session_id=session_id, after_seq=after_seq)

    def session_messages(self, *, session_id: str, limit: int = 50) -> list[dict[str, Any]]:
        # 从事件中派生 chat messages（用户/助手）
        msgs: list[dict[str, Any]] = []
        for e in self.eventlog.events:
            if e.get("session_id") != session_id:
                continue
            et = e.get("type")
            payload = e.get("payload") or {}
            if et == "inbound_message":
                text = payload.get("text")
                if isinstance(text, str):
                    msgs.append({"role": "user", "content": text})
            elif et == "outbound_message":
                text = payload.get("text")
                if isinstance(text, str):
                    msgs.append({"role": "assistant", "content": text})
            elif et == "tool_result":
                # 将工具结果以“canonical trace”形式塞回上下文（摘要版）。
                name = payload.get("name")
                summary = payload.get("summary")
                arguments = payload.get("arguments")
                task_id = payload.get("task_id")
                ref = payload.get("ref")

                if not isinstance(name, str) or not name:
                    continue
                if not isinstance(summary, str) or not summary:
                    continue

                try:
                    args_json = json.dumps(arguments, ensure_ascii=False) if isinstance(arguments, dict) else "{}"
                except Exception:
                    args_json = "{}"
                if len(args_json) > 240:
                    args_json = args_json[:240] + "...<truncated>"

                tid = str(task_id) if task_id else ""
                content = (
                    "[CLONOTH_TOOL_TRACE v1]\n"
                    + (f"TASK: {tid}\n" if tid else "")
                    + f"TOOL_CALL: {name} {args_json}\n"
                    + f"TOOL_RESULT_SUMMARY: {summary}\n"
                    + f"TOOL_RESULT_REF: {str(ref) if ref else ''}\n"
                    + "[/CLONOTH_TOOL_TRACE]"
                )
                msgs.append({"role": "assistant", "content": content})

        if limit > 0:
            msgs = msgs[-limit:]
        return msgs

    def admin_state(self) -> AdminStateOut:
        task_counts = {s.value: 0 for s in TaskStatus}
        for t in self.tasks.values():
            task_counts[t.status.value] = task_counts.get(t.status.value, 0) + 1

        approval_counts = {s.value: 0 for s in ApprovalStatus}
        pending: list[Approval] = []
        for a in self.approvals.values():
            approval_counts[a.status.value] = approval_counts.get(a.status.value, 0) + 1
            if a.status == ApprovalStatus.pending:
                pending.append(a)

        return AdminStateOut(
            sessions=len(self.sessions),
            tasks=task_counts,
            approvals=approval_counts,
            pending_approvals=pending,
        )

    def write_boot_event(self) -> dict[str, Any]:
        prev = self.eventlog.last_boot_run_id()
        payload = {
            "previous_run_id": prev,
            "restarted": prev is not None,
            "ts": _now().isoformat(),
        }
        return self.eventlog.append(session_id=SYSTEM_SESSION_ID, component="supervisor", type_="boot", payload=payload)
